import type { Metadata } from "next";
import Provider from "@/components/providers/provider";

export const metadata: Metadata = {
  title: "Editor | Profiles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <Provider>
    {children}
   </Provider>
  );
}
