
import Bento from '@/components/landing/bento'
import Footer from '@/components/landing/footer'
import Hero from '@/components/landing/hero'
import HeroImage from '@/components/landing/hero-img'
import Navbar from '@/components/landing/navbar'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { SignedIn, SignedOut } from '@clerk/nextjs'
import { UserIcon, Zap } from 'lucide-react'
import { Metadata } from 'next'
import Link from 'next/link'
import React from 'react'

export const metadata: Metadata = {
  title: " Profiles",
  description: "Generated by create next app",
};

const page = () => {
  return (
  <div className='w-full h-full  bg-zinc-950'>
      <div className='w-full max-w-[1300px]  h-full px-2 py-5 mx-auto'>
      <Navbar/>
    <Hero/> 
    <HeroImage/>
    <Bento/>
    </div>
    <Footer/>
  </div>
  )
}

export default page